# Generated by Django 4.2.1 on 2023-08-12 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputhistory",
            name="timestamp",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2023, 8, 12, 23, 48, 13, 789775)
            ),
        ),
    ]
