# Generated by Django 4.2.1 on 2023-08-12 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_inputhistory_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputhistory",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 23, 50, 33, 73007)
            ),
        ),
    ]
