# Generated by Django 4.2.1 on 2023-08-16 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_inputhistory_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputhistory",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 16, 7, 6, 41, 521591, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(
            name="LoginHistory",
        ),
    ]
